<?php

/**
 * Implements hook_sheetnode_plugins().
 */
function sheetnode_ethercalc_sheetnode_plugins($value, $save_element, $context) {
  // Only turn on Ethercalc if we're editing the node.
  if (!empty($save_element)) {
    $ethercalc_host = variable_get('sheetnode_ethercalc_host', '');
    $ethercalc_port = variable_get('sheetnode_ethercalc_port', '8000');

    $ethercalc_path = $GLOBALS['base_url'];
    $ethercalc_path = preg_replace('/(:\\/\\/[^\\/]+).*/', '$1', $ethercalc_path, 1);
    if ($ethercalc_port) {
        $ethercalc_path = preg_replace('/(?:\:\d+)?$/', (':' . $ethercalc_port), $ethercalc_path, 1);
    }
    if ($ethercalc_host) {
        $ethercalc_path = preg_replace('/^([^:]*)/', $ethercalc_host, $ethercalc_path, 1);
    }

    drupal_add_js($ethercalc_path . '/socket.io/socket.io.js#',    array('weight' => 10));
    drupal_add_js($ethercalc_path . '/zappa/zappa.js#',            array('weight' => 10));
    drupal_add_js($ethercalc_path . '/player-broadcast.js#',       array('weight' => 10));
    drupal_add_js($ethercalc_path . '/player.js#',                 array('weight' => 10));
  }
}

/**
 * Implements hook_menu().
 */
function sheetnode_ethercalc_menu() {
  $items = array();

  $items['admin/config/content/sheetnode/ethercalc'] = array(
    'title' => 'EtherCalc',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_sheetnode_ethercalc_settings'),
    'description' => 'Administer settings for Sheetnode EtherCalc.',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Form function for admin/settings/sheetnode/ethercalc.
 */
function _sheetnode_ethercalc_settings($form, &$form_state) {
  $form['sheetnode_ethercalc_host'] = array(
    '#type' => 'textfield',
    '#title' => t('EtherCalc host'),
    '#description' => t('Enter the domain name of the EtherCalc server. Leave blank to use same domain as your Drupal installation.'),
    '#default_value' => variable_get('sheetnode_ethercalc_host', ''),
  );
  $form['sheetnode_ethercalc_port'] = array(
    '#type' => 'textfield',
    '#title' => t('EtherCalc port'),
    '#description' => t('Enter the port of the EtherCalc server.'),
    '#default_value' => variable_get('sheetnode_ethercalc_port', '8000'),
  );
  return system_settings_form($form);
}

